# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM docker.m-chain.com/_BASE_NS_/mchain-baseos:_BASE_TAG_
ENV FABRIC_CFG_PATH /etc/hyperledger/mchain
RUN mkdir -p /var/hyperledger/production $FABRIC_CFG_PATH
COPY payload/peer /usr/local/bin
ADD  payload/sampleconfig.tar.bz2 $FABRIC_CFG_PATH
CMD ["peer","node","start"]
